// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvmsyayyaevsiatbzqdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2bXN5YXl5YWV2c2lhdGJ6cWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTE1MzMsImV4cCI6MjA2NTIyNzUzM30.PdBjEZbjLs8ARzZaQWQ0aFALygrfHqwHLtt0G4mSC5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);